name: Mirror to Gitee

on:
  push:
    branches: [master]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Gitee
        run: |
          git remote add gitee https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/ymxy_1_0/manon.git
          git push gitee master --force
